"""Single direct Sarvam AI client used by all AI features."""

import json
import time
import urllib.error
import urllib.request
from typing import Any, Dict, List, Optional

from app.config import settings

SARVAM_URL = "https://api.sarvam.ai/v1/chat/completions"
MAX_ATTEMPTS = 3
TIMEOUT_SECONDS = 75


def _extract_text(payload: Dict[str, Any]) -> str:
    choices = payload.get("choices") or []
    if not choices:
        return ""
    message = choices[0].get("message") or {}
    content = message.get("content")
    if isinstance(content, str):
        return content.strip()
    if isinstance(content, list):
        parts: List[str] = []
        for item in content:
            if isinstance(item, str):
                parts.append(item)
            elif isinstance(item, dict):
                text = item.get("text") or item.get("content")
                if isinstance(text, str):
                    parts.append(text)
        return "\n".join(p.strip() for p in parts if p.strip()).strip()
    return str(content).strip() if content is not None else ""


def _request(messages: List[Dict[str, str]], *, json_mode: bool = False, max_tokens: int = 4096) -> Dict[str, Any]:
    settings.require_llm()
    body: Dict[str, Any] = {
        "model": settings.llm_model,
        "messages": messages,
        "temperature": 0.2,
        "max_tokens": max_tokens,
        "reasoning_effort": "low",
    }
    if json_mode:
        body["response_format"] = {"type": "json_object"}

    request = urllib.request.Request(
        SARVAM_URL,
        data=json.dumps(body).encode("utf-8"),
        method="POST",
        headers={
            "Content-Type": "application/json",
            "Accept": "application/json",
            "api-subscription-key": settings.llm_api_key or "",
        },
    )

    last_error: Optional[Exception] = None
    for attempt in range(1, MAX_ATTEMPTS + 1):
        try:
            with urllib.request.urlopen(request, timeout=TIMEOUT_SECONDS) as response:
                raw = response.read().decode("utf-8")
                return json.loads(raw)
        except urllib.error.HTTPError as exc:
            body_text = exc.read().decode("utf-8", errors="replace")
            last_error = RuntimeError(f"Sarvam API HTTP {exc.code}: {body_text[:1000]}")
            if exc.code not in {408, 409, 429, 500, 502, 503, 504} or attempt == MAX_ATTEMPTS:
                raise last_error from exc
        except (urllib.error.URLError, TimeoutError, json.JSONDecodeError) as exc:
            last_error = exc
            if attempt == MAX_ATTEMPTS:
                raise RuntimeError(f"Sarvam API request failed: {exc}") from exc
        if attempt < MAX_ATTEMPTS:
            time.sleep(1.5 * attempt)

    raise RuntimeError(f"Sarvam API request failed: {last_error}")


def chat(messages: List[Dict[str, str]], *, max_tokens: int = 4096) -> str:
    """Return plain assistant text from Sarvam."""
    answer = _extract_text(_request(messages, max_tokens=max_tokens))
    if not answer:
        raise RuntimeError("Sarvam AI returned an empty response.")
    return answer


def chat_json(messages: List[Dict[str, str]], *, max_tokens: int = 4096) -> Dict[str, Any]:
    """Return a JSON object generated by Sarvam."""
    answer = _extract_text(_request(messages, json_mode=True, max_tokens=max_tokens))
    if not answer:
        raise RuntimeError("Sarvam AI returned an empty JSON response.")
    try:
        return json.loads(answer)
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"Sarvam AI returned invalid JSON: {answer[:1000]}") from exc
