"""
Evaluation harness (Module in spec section 8 -- "do not just demo it, measure it").

Responsibility: run the real pipeline (not mocks) against a fixed test set
and write the results into reports/answer_quality.md, so grading is backed
by actual numbers rather than a live demo going well once.

- Retrieval quality: for sample resumes, does search_jobs() surface a job
  matching the expected title?
- Answer quality:    for mentor questions, is the answer grounded in its
  retrieved sources (per src/safety/guardrails.is_grounded), and does it
  cover the keywords a correct answer should mention?
- Hallucination check: a question with no answer in career_notes/ should
  produce an honest "I don't know" -- also scored as grounded.

This file never invents numbers: every score below comes from actually
calling parse/search/mentor. Run it after LLM_API_KEY is set and both FAISS
indexes exist (build them with job_search.py --build and
mentor.rag_chain.build_mentor_index()).
"""

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List

from src.config import load_config
from src.mentor.rag_chain import ask_mentor
from src.search.job_search import search_jobs

DEFAULT_TEST_SET_PATH = Path("reports/eval_test_set.json")
DEFAULT_REPORT_PATH = Path("reports/answer_quality.md")


def load_test_set(path: Path = DEFAULT_TEST_SET_PATH) -> Dict[str, Any]:
    """Load the fixed evaluation questions and expected sources."""
    if not path.exists():
        raise FileNotFoundError(
            f"No test set at '{path}'. Copy/edit the starter file at that path "
            "with your own resumes and mentor questions."
        )
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def evaluate_retrieval(test_set: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Score retrieval quality over the test set's job-match profiles."""
    rows = []
    for case in test_set.get("job_match_profiles", []):
        results = search_jobs(case["resume_text"], top_k=case.get("top_k", 5))
        expected = case["expected_job_title_contains"].lower()
        hit = any(expected in r["title"].lower() for r in results)
        rank = next((i + 1 for i, r in enumerate(results) if expected in r["title"].lower()), None)
        rows.append(
            {
                "query": case.get("label", case["resume_text"][:40] + "..."),
                "expected_source": case["expected_job_title_contains"],
                "retrieved": hit,
                "rank": rank,
            }
        )
    return rows


def evaluate_answers(test_set: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Score mentor answer quality over the test set's questions."""
    rows = []
    for case in test_set.get("mentor_questions", []):
        result = ask_mentor(case["question"])
        answer_lower = result["answer"].lower()
        keywords = case.get("expected_keywords", [])
        relevance = (
            sum(1 for kw in keywords if kw.lower() in answer_lower) / len(keywords) if keywords else None
        )
        rows.append(
            {
                "question": case["question"],
                "relevance": relevance,
                "grounded": result["grounded"],
                "comment": "blocked by guardrails" if result["blocked"] else "",
            }
        )
    return rows


def write_report(
    retrieval_rows: List[Dict[str, Any]],
    answer_rows: List[Dict[str, Any]],
    report_path: Path = DEFAULT_REPORT_PATH,
) -> None:
    """Write scored results into reports/answer_quality.md."""
    hit_count = sum(1 for r in retrieval_rows if r["retrieved"])
    hit_rate = f"{hit_count}/{len(retrieval_rows)}" if retrieval_rows else "n/a"
    grounded_count = sum(1 for a in answer_rows if a["grounded"])
    grounded_rate = f"{grounded_count}/{len(answer_rows)}" if answer_rows else "n/a"

    lines = [
        "# Answer Quality Report",
        "",
        f"Generated by `src/evaluate.py` on {datetime.now(timezone.utc).isoformat(timespec='seconds')}.",
        "",
        "## 1. Method",
        "Fixed test set at `reports/eval_test_set.json`, run against the live pipeline "
        "(no mocked results) via `python -m src.evaluate`.",
        "",
        "## 2. Retrieval quality",
        f"Hit rate: **{hit_rate}** (expected job title appeared in top-k results).",
        "",
        "| Query | Expected source | Retrieved? | Rank | Notes |",
        "|---|---|---|---|---|",
    ]
    for r in retrieval_rows:
        lines.append(f"| {r['query']} | {r['expected_source']} | {r['retrieved']} | {r['rank'] or '-'} | |")

    lines += [
        "",
        "## 3. Mentor answer quality",
        f"Grounded rate: **{grounded_rate}** (answer supported by retrieved career notes, "
        "or an honest refusal).",
        "",
        "| Question | Relevance | Grounded | Comment |",
        "|---|---|---|---|",
    ]
    for a in answer_rows:
        rel = f"{a['relevance']:.0%}" if a["relevance"] is not None else "n/a"
        lines.append(f"| {a['question']} | {rel} | {a['grounded']} | {a['comment']} |")

    lines += [
        "",
        "## 4. Failure cases",
        "Review the rows above with `Retrieved? = False` or `Grounded = False` and describe why.",
        "",
        "## 5. Prompt iterations",
        "Document at least one before/after prompt change here (see spec section 8).",
        "",
        "## 6. Conclusions",
        "",
    ]

    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    load_config()  # fail fast with a clear message if data dirs are missing
    test_set = load_test_set()
    retrieval_rows = evaluate_retrieval(test_set)
    answer_rows = evaluate_answers(test_set)
    write_report(retrieval_rows, answer_rows)
    print(f"Wrote {DEFAULT_REPORT_PATH} with {len(retrieval_rows)} retrieval case(s) "
          f"and {len(answer_rows)} mentor question(s).")
